export type Task={id:number,text:string,done:boolean,dueAt?:number,repeat?:'none'|'daily'|'weekly',notifiedAt?:number,snoozeUntil?:number};
export type ReminderAlert={taskId:number,text:string,scheduledAt:number};
export function readTasks(raw:string|null):Task[]{try{const data=JSON.parse(raw||'[]');if(!Array.isArray(data))return [];return data.filter(t=>t&&Number.isFinite(t.id)&&typeof t.text==='string'&&typeof t.done==='boolean').map(t=>({id:t.id,text:t.text,done:t.done,...(Number.isFinite(t.dueAt)?{dueAt:t.dueAt}:{}),repeat:['daily','weekly'].includes(t.repeat)?t.repeat:'none',...(Number.isFinite(t.notifiedAt)?{notifiedAt:t.notifiedAt}:{}),...(Number.isFinite(t.snoozeUntil)?{snoozeUntil:t.snoozeUntil}:{})}));}catch{return [];}}
export function nextOccurrence(dueAt:number,repeat:'daily'|'weekly',now:number){const date=new Date(dueAt);const step=repeat==='daily'?1:7;const elapsed=Math.max(0,Math.floor((now-dueAt)/86400000));date.setDate(date.getDate()+Math.max(step,Math.floor(elapsed/step)*step));while(date.getTime()<=now)date.setDate(date.getDate()+step);return date.getTime();}
export function collectDue(tasks:Task[],now:number){const alerts:ReminderAlert[]=[];const updated=tasks.map(task=>{if(task.done||!Number.isFinite(task.dueAt))return task;
if(task.snoozeUntil){if(task.snoozeUntil>now)return task;alerts.push({taskId:task.id,text:task.text,scheduledAt:task.snoozeUntil});return {...task,snoozeUntil:undefined};}
if(task.dueAt!>now||task.notifiedAt===task.dueAt)return task;alerts.push({taskId:task.id,text:task.text,scheduledAt:task.dueAt!});return {...task,notifiedAt:task.dueAt,...(task.repeat==='daily'||task.repeat==='weekly'?{dueAt:nextOccurrence(task.dueAt!,task.repeat,now)}:{})};});return {tasks:updated,alerts};}
export function isReminderRequest(text:string){return /\b(lembrete|lembre|lembrar|alarme|despertador|me avise|me avisar)\b/i.test(text);}
export function parseReminder(text:string,now:number):{title:string,dueAt:number}|null{
if(!isReminderRequest(text))return null;
const cleanTitle=(value:string)=>value.replace(/^\s*(?:ciço doido[, ]*)?(?:por favor[, ]*)?(?:(?:crie|criar|cria|coloque|colocar|configure|agende|marque|defina|quero|preciso de)\s+)?(?:um\s+)?(?:me lembre|lembre-me|lembrar|lembrete|alarme|despertador|me avise|me avisar)(?:\s+(?:de|para|pra))?\s*/i,'').replace(/(?:^|\s)(hoje|amanhã|amanha)(?=\s|$|[,!.])/gi,'').replace(/^(?:para|pra|de)\s+/i,'').replace(/\s+/g,' ').replace(/^[, .]+|[, .]+$/g,'').trim();
const delay=text.match(/(?:em|daqui\s+a)\s+(\d+)\s*(segundos?|minutos?|horas?)\b/i);if(delay){const amount=Number(delay[1]);const unit=/^hora/i.test(delay[2])?3600000:/^minuto/i.test(delay[2])?60000:1000;if(amount<1||amount*unit>366*86400000)return null;const title=cleanTitle(text.replace(delay[0],''))||'Alarme';return {title,dueAt:now+amount*unit};}
const clock=text.match(/(?:às|as|para\s+as|pras)\s+(\d{1,2})(?:(?::|h)(\d{2})?)?(?:\s*horas?)?\b/i)||text.match(/\b(\d{1,2})(?::(\d{2})|h(\d{2})?)\b/i);if(!clock)return null;const h=Number(clock[1]),m=Number(clock[2]||clock[3]||0);if(h>23||m>59)return null;const date=new Date(now);date.setHours(h,m,0,0);if(/(?:^|\s)amanh[ãa](?=\s|$|[,!.])/i.test(text))date.setDate(date.getDate()+1);else if(date.getTime()<=now){if(/\bhoje\b/i.test(text))return null;date.setDate(date.getDate()+1);}const title=cleanTitle(text.replace(clock[0],''))||'Alarme';return {title,dueAt:date.getTime()};
}
export function calendarEvent(task:Task){if(!task.dueAt)return '';const stamp=(n:number)=>new Date(n).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const escape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cico Doido//Lembretes//PT-BR','BEGIN:VEVENT','UID:'+task.id+'@cico-doido','DTSTAMP:'+stamp(Date.now()),'DTSTART:'+stamp(task.dueAt),'DTEND:'+stamp(task.dueAt+60000),'SUMMARY:'+escape(task.text),...(task.repeat==='daily'||task.repeat==='weekly'?['RRULE:FREQ='+ (task.repeat==='daily'?'DAILY':'WEEKLY')]:[]),'BEGIN:VALARM','ACTION:DISPLAY','TRIGGER:PT0S','DESCRIPTION:'+escape(task.text),'END:VALARM','END:VEVENT','END:VCALENDAR'].join('\r\n');}
